### PR TITLE
Parameters set/get works

### PR DESCRIPTION
**Pull request by ghost**
```
void usage(const char* app_name)
{
    std::cout << "usage :\n";
    std::cout << "1) write firmware to PlayUAV OSD board from <from_filename>\n";
    std::cout << "      " << app_name << " -fw_w <from_filename>\n\n";
    std::cout << "2) set parameters to PlayUAV OSD board from <from_filename>\n";
    std::cout << "      " << app_name << " -pm_w <from_filename>\n\n";
    std::cout << "3) set default parameters to PlayUAV OSD board\n";
    std::cout << "      " << app_name << " -pm_w\n\n";
    std::cout << "4) get parameters from PlayUAV OSD board and save to <to_filename>\n";
    std::cout << "      " << app_name << " -pm_r <to_filename>\n\n";
    std::cout << "(TODO: read, verify, erase_all, erase_sectors, upload to eeprom)\n\n";
}
```

I have tested all the functions and they worked fine. But there is still a bug in function COSDConn::get_params. After getting the parameters from board, we should get a sync but not.

### CODE REVIEW

**Comment by kwikius** [comment]
Hi Tom,

 Looks like a great addition. Not looked in detail yet, but the bugs may have to do with my implementation of serial port, whichs adds a hidden terminating zero character to string literals, which could be considered surprising behaviour. I recently added another version of the function called write_strlen which doesnt send the zero. https://github.com/kwikius/quan-trunk/blob/master/quan/platform/linux/serial_port.hpp#L67

I will look into it today if possible.

regards
Andy

**Comment by kwikius** [comment]
Hi Tom,

Not really a fan of the '_' prefix on private member functions. As a compromise hope you ok to change that to 'm_' ?

regards
Andy

**Comment by ghost** [comment]
Hi Andy,

Changed the coding style. 

The issue may happen at the serial_port::read. The codes work fine when I comment the line "_getSync();" after getting the parameters from board. https://github.com/rentt/PlayUAVOSDUploadHack/blob/params/osdconn.cpp#L221

Regards,
Tom

**Comment by kwikius** [comment]
Hi Tom,

Merged  Did some testing today. Works fast. Great for makefiles etc
As to the sync issues, we will have to wait see if its a problem. Seemed to work fine though
I added some licences info too.

**Pull request closed without merging**
